import { createBrowserRouter, Navigate, Outlet } from "react-router-dom";
import Root from "./components/Root";
import Home from "./components/Home";
import Login from "./components/Login";
import SignUp from "./components/SignUp";
import ForgotPassword from "./components/ForgotPassword";
import ResetPassword from "./components/ResetPassword";
import DesignSystem from "./components/DesignSystem";
import FigmaDesignGallery from "./components/FigmaDesignGallery";
import MenuShowcase from "./components/MenuShowcase";
import Insights from "./components/Insights";
import Administration from "./components/Administration";
import CreateSpace from "./components/CreateSpace";
import CreateUnit from "./components/CreateUnit";
import AddUnits from "./components/AddUnits";
import AutoGeneratedUnits from "./components/AutoGeneratedUnits";
import ManualAddUnit from "./components/ManualAddUnit";
import CreatedUnits from "./components/CreatedUnits";
import CreateLease from "./components/CreateLease";
import CreateCustomer from "./components/CreateCustomer";
import CreatePricing from "./components/CreatePricing";
import CreateDocuments from "./components/CreateDocuments";
import ManageSpaces from "./components/ManageSpaces";
import EditSpace from "./components/EditSpace";
import AddFloor from "./components/AddFloor";
import ManageUnits from "./components/ManageUnits";
import ManageUnitsView from "./components/ManageUnitsView";
import EditUnit from "./components/EditUnit";
import EditUnitWrapper from "./components/EditUnitWrapper";
import ManageLeases from "./components/ManageLeases";
import EditLease from "./components/EditLease";
import ManageCustomers from "./components/ManageCustomers";
import EditCustomer from "./components/EditCustomer";
import ManagePricing from "./components/ManagePricing";
import ManageBookings from "./components/ManageBookings";
import ManagePayments from "./components/ManagePayments";
import NotificationCenterPage from "./components/NotificationCenterPage";

const ProtectedRoute = () => {
  const token = localStorage.getItem("authToken");

  if (!token) {
    return <Navigate to="/login" replace />;
  }

  return <Outlet />;
};

export const router = createBrowserRouter([
  { path: "/login", Component: Login },
  { path: "/signup", Component: SignUp },
  { path: "/forgot-password", Component: ForgotPassword },
  { path: "/reset-password/:token", Component: ResetPassword },

  {
  element: <ProtectedRoute />,
  children: [
    {
      element: <Root />,
      children: [
        { path: "/root", element: <Home /> },
        { path: "/home", element: <Home /> },
        { path: "/notifications", element: <NotificationCenterPage /> },

        { path: "/create", element: <Navigate to="/create/space" replace /> },
        { path: "/create/space", element: <CreateSpace /> },
        { path: "/create/units", element: <CreateUnit /> },
        { path: "/create/units/configure", element: <AddUnits />, id: "create-units-configure" },
        { path: "/create/units/auto-generated", element: <AutoGeneratedUnits /> },
        { path: "/create/units/manual-add", element: <ManualAddUnit /> },
        { path: "/create/created-units", element: <CreatedUnits /> },
        { path: "/create/lease", element: <CreateLease /> },
        { path: "/create/customer", element: <CreateCustomer /> },
        { path: "/create/pricing", element: <CreatePricing /> },
        { path: "/create/documents", element: <CreateDocuments /> },

        { path: "/manage", element: <Navigate to="/manage/spaces" replace /> },
        { path: "/manage/spaces", element: <ManageSpaces /> },
        { path: "/manage/edit-space/:spaceId", element: <EditSpace /> },
        { path: "/manage/add-floor/:spaceId", element: <AddFloor /> },
        { path: "/manage/edit-unit/:spaceId/:unitId", element: <EditUnit /> },
        { path: "/manage/edit-unit/:unitId", element: <EditUnitWrapper /> },
        { path: "/manage/units", element: <ManageUnits /> },
        { path: "/manage/units/:spaceId", element: <ManageUnits /> },
        { path: "/manage/units-view", element: <ManageUnitsView /> },
        { path: "/manage/leases", element: <ManageLeases /> },
        { path: "/manage/edit-lease/:leaseId", element: <EditLease /> },
        { path: "/manage/documents", element: <CreateDocuments /> },
        { path: "/manage/customers", element: <ManageCustomers /> },
        { path: "/manage/edit-customer/:customerId", element: <EditCustomer /> },
        { path: "/manage/pricing", element: <ManagePricing /> },
        { path: "/manage/bookings", element: <ManageBookings /> },
        { path: "/manage/payments", element: <ManagePayments /> },

        { path: "/insights", element: <Insights /> },
        { path: "/administration", element: <Administration /> },
      ],
    },
  ],
},

  { path: "/menus", Component: MenuShowcase },
  { path: "/design-system", Component: DesignSystem },
  { path: "/figma-35", Component: FigmaDesignGallery },

  { path: "/", element: <Navigate to="/login" replace /> },
  { path: "*", element: <Navigate to="/login" replace /> },
]);