import React, { useEffect, useState } from 'react';
import api from '../src/api/axios';
import { ArrowLeft, BarChart3, Building2, MapPin, Sparkles, Wand2 } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';

type LocationState = {
  spaceId?: string;
};
type SelectedSpace = {
  name: string;
  type: string;
  location: string;
};

export default function AutoGeneratedUnits() {
  const navigate = useNavigate();
  const location = useLocation();
  const state = (location.state as LocationState) || {};
  const selectedId = state.spaceId || localStorage.getItem('selectedSpaceId') || '';

const [selectedSpace, setSelectedSpace] = useState<SelectedSpace | null>(null);
const [loadingSpace, setLoadingSpace] = useState(Boolean(selectedId));

useEffect(() => {
  if (!selectedId) {
    setLoadingSpace(false);
    return;
  }

  localStorage.setItem('selectedSpaceId', selectedId);

  let active = true;

  api.get(`/spaces/${selectedId}`)
    .then((response) => {
      const space = response.data?.data || response.data;

      if (active) {
        setSelectedSpace({
          name: space.name || space.space_name || 'Selected Space',
          type: space.type || space.space_type || 'Space',
          location: space.address || space.location || '-',
        });
      }
    })
    .catch((error) => {
      console.error('Failed to fetch selected space:', error);
    })
    .finally(() => {
      if (active) setLoadingSpace(false);
    });

  return () => {
    active = false;
  };
}, [selectedId]);

  return (
    <div style={{ padding: '12px 10px 20px', backgroundColor: '#eef2f6', minHeight: '100vh' }}>
      <div style={{ maxWidth: '1060px', margin: '0 auto' }}>
        <button
            type="button"
            onClick={() => navigate('/manage/units')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              border: 'none',
              backgroundColor: 'transparent',
              color: '#7b8da2',
              fontSize: '11px',
              cursor: 'pointer',
              marginBottom: '6px',
              padding: 0,
            }}
          >
            <ArrowLeft size={12} /> Back to Selection
          </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
          <div
            style={{
              width: '34px',
              height: '34px',
              borderRadius: '10px',
              backgroundColor: 'var(--spacespot-cyan-primary)',
              display: 'grid',
              placeItems: 'center',
              boxShadow: '0 6px 10px rgba(20, 216, 204, 0.2)',
            }}
          >
            <Sparkles size={16} color="#ffffff" />
          </div>
          <div style={{ fontSize: '22px', color: 'var(--spacespot-navy-primary)', fontWeight: 600 }}>Auto-Generate Units</div>
        </div>
        <div style={{ width: '56px', height: '2px', backgroundColor: '#8adfd7', marginBottom: '12px', borderRadius: '999px' }} />

        <div
          style={{
            backgroundColor: '#ffffff',
            border: '1.5px solid #9fe5df',
            borderRadius: '8px',
            padding: '10px 12px',
            display: 'grid',
            gridTemplateColumns: '1fr 1fr 1fr 1fr',
            gap: '8px',
            marginBottom: '10px',
          }}
        >
          <div>
            <div style={{ fontSize: '8px', color: '#8ea0b4', marginBottom: '4px', letterSpacing: '0.04em' }}>SPACE ID</div>
            <div style={{ fontSize: '22px', lineHeight: 1, color: 'var(--spacespot-navy-primary)', fontWeight: 700 }}>{selectedId}</div>
          </div>

          <div>
            <div style={{ fontSize: '8px', color: '#8ea0b4', marginBottom: '4px', letterSpacing: '0.04em' }}>SPACE NAME</div>
            <div style={{ fontSize: '16px', color: 'var(--spacespot-navy-primary)', fontWeight: 600 }}>{loadingSpace ? 'Loading...' : selectedSpace?.name || 'No space selected'}</div>
          </div>

          <div>
            <div style={{ fontSize: '8px', color: '#8ea0b4', marginBottom: '4px', letterSpacing: '0.04em' }}>TYPE</div>
            <span
              style={{
                display: 'inline-block',
                fontSize: '10px',
                color: '#16bfb6',
                border: '1px solid #c9ebe7',
                backgroundColor: '#ecfbf9',
                borderRadius: '999px',
                padding: '2px 8px',
                fontWeight: 600,
              }}
            >
              {loadingSpace ? 'Loading...' : selectedSpace?.type || '-'}
            </span>
          </div>

          <div>
            <div style={{ fontSize: '8px', color: '#8ea0b4', marginBottom: '4px', letterSpacing: '0.04em' }}>LOCATION</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '5px', fontSize: '10px', color: '#6b7e91' }}>
              <MapPin size={10} color="#9aacc0" />
              {loadingSpace ? 'Loading...' : selectedSpace?.location || '-'}
            </div>
          </div>
        </div>

        <div
          style={{
            backgroundColor: '#ffffff',
            border: '1.5px solid #9fe5df',
            borderRadius: '8px',
            padding: '14px',
          }}
        >
          <div
            style={{
              border: '1px solid #b6e9e4',
              borderRadius: '8px',
              padding: '12px 12px 14px',
              marginBottom: '10px',
              backgroundColor: '#f8fdfd',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <div
                style={{
                  width: '24px',
                  height: '24px',
                  borderRadius: '6px',
                  backgroundColor: 'var(--spacespot-cyan-primary)',
                  display: 'grid',
                  placeItems: 'center',
                }}
              >
                <Sparkles size={12} color="#ffffff" />
              </div>
              <div>
                <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--spacespot-navy-primary)' }}>Describe</div>
                <div style={{ fontSize: '9px', color: '#95a5b8' }}>Describe what units you want to create and AI will generate them for you</div>
              </div>
            </div>

            <textarea
              rows={4}
              placeholder="Example: create 10 units in my level -1 with varying sizes from 10-50 sqm for retail purposes"
              style={{
                width: '100%',
                border: '1px solid #a9b9ca',
                borderRadius: '6px',
                fontSize: '10px',
                color: '#203249',
                padding: '9px 10px',
                resize: 'vertical',
                boxSizing: 'border-box',
                backgroundColor: '#ffffff',
                marginBottom: '10px',
              }}
            />

            <button
              type="button"
              style={{
                border: 'none',
                backgroundColor: 'var(--spacespot-navy-primary)',
                borderRadius: '6px',
                color: '#ffffff',
                fontSize: '10px',
                height: '28px',
                padding: '0 10px',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                cursor: 'pointer',
                fontWeight: 600,
              }}
            >
              <Sparkles size={12} /> Generate from Description
            </button>
          </div>

          <div
            style={{
              border: '1px solid #b6e9e4',
              borderRadius: '8px',
              padding: '10px 12px',
              marginBottom: '10px',
              backgroundColor: '#f8fdfd',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <div
                style={{
                  width: '24px',
                  height: '24px',
                  borderRadius: '6px',
                  backgroundColor: 'var(--spacespot-cyan-primary)',
                  display: 'grid',
                  placeItems: 'center',
                }}
              >
                <Building2 size={12} color="#ffffff" />
              </div>
              <div>
                <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--spacespot-navy-primary)' }}>Use Map</div>
                <div style={{ fontSize: '9px', color: '#95a5b8' }}>
                  Use map if uploaded and suggest the best possible location for rentable units and generate units
                </div>
              </div>
            </div>
            <button
              type="button"
              style={{
                border: 'none',
                backgroundColor: 'var(--spacespot-navy-primary)',
                borderRadius: '6px',
                color: '#ffffff',
                fontSize: '10px',
                height: '28px',
                padding: '0 10px',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                cursor: 'pointer',
                fontWeight: 600,
              }}
            >
              <Building2 size={12} /> Generate from Map
            </button>
          </div>

          <div
            style={{
              border: '1px solid #b6e9e4',
              borderRadius: '8px',
              padding: '10px 12px',
              backgroundColor: '#f8fdfd',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <div
                style={{
                  width: '24px',
                  height: '24px',
                  borderRadius: '6px',
                  backgroundColor: 'var(--spacespot-cyan-primary)',
                  display: 'grid',
                  placeItems: 'center',
                }}
              >
                <BarChart3 size={12} color="#ffffff" />
              </div>
              <div>
                <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--spacespot-navy-primary)' }}>Use Data</div>
                <div style={{ fontSize: '9px', color: '#95a5b8' }}>Analyse foot traffic data to suggest creation units</div>
              </div>
            </div>
            <button
              type="button"
              style={{
                border: 'none',
                backgroundColor: 'var(--spacespot-navy-primary)',
                borderRadius: '6px',
                color: '#ffffff',
                fontSize: '10px',
                height: '28px',
                padding: '0 10px',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                cursor: 'pointer',
                fontWeight: 600,
              }}
            >
              <Wand2 size={12} /> Generate from Data
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

